"""Second migration

Revision ID: 7d6f0389e7dd
Revises: 00a4968327ea
Create Date: 2021-11-08 19:59:05.412114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6f0389e7dd'
down_revision = '00a4968327ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('pitches', sa.Column('category', sa.String(length=25), nullable=True))
    op.drop_column('pitches', 'pCategory')
    op.drop_column('pitches', 'pId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pId', sa.INTEGER(), server_default=sa.text('nextval(\'"pitches_pId_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.add_column('pitches', sa.Column('pCategory', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'category')
    op.drop_column('pitches', 'id')
    # ### end Alembic commands ###
